default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres

development:
  <<: *default
  database: rails_tutorial01_development

test:
  <<: *default
  database: rails_tutorial01_test

production:
  <<: *default
  database: rails_tutorial01_production
